#include "Graphic.cpp"
#include "GraphicDef.cpp"

#include "Device/GraphicDevice.cpp"
#include "CommandQueue/GraphicCommandQueue.cpp"
#include "CommandList/GraphicCommandList.cpp"
#include "SwapChain/GraphicSwapChain.cpp"
#include "Buffer/GraphicBuffer.cpp"
#include "Fence/GraphicFence.cpp"
#include "Viewport/GraphicViewport.cpp"
#include "ScissorRect/GraphicScissorRect.cpp"
#include "Descriptor/GraphicDescriptor.cpp"
#include "Descriptor/Handle/CPU/GraphicDescriptorCpuHandle.cpp"
#include "Descriptor/Handle/GPU/GraphicDescriptorGpuHandle.cpp"

#if PLATFORM_WIN
#include "Platform/Win/GraphicImpl.cpp"
#include "Platform/Win/GraphicDefWin.cpp"
#include "Platform/Win/Device/GraphicDeviceImpl.cpp"
#include "Platform/Win/CommandQueue/GraphicCommandQueueImpl.cpp"
#include "Platform/Win/CommandList/GraphicCommandListImpl.cpp"
#include "Platform/Win/SwapChain/GraphicSwapChainImpl.cpp"
#include "Platform/Win/Buffer/GraphicBufferImpl.cpp"
#include "Platform/Win/Fence/GraphicFenceImpl.cpp"
#include "Platform/Win/Viewport/GraphicViewportImpl.cpp"
#include "Platform/Win/ScissorRect/GraphicScissorRectImpl.cpp"
#include "Platform/Win/Descriptor/GraphicDescriptorImpl.cpp"
#include "Platform/Win/Descriptor/Handle/CPU/GraphicDescriptorCpuHandleImpl.cpp"
#include "Platform/Win/Descriptor/Handle/GPU/GraphicDescriptorGpuHandleImpl.cpp"
#endif // PLATFORM_WIN